
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.FileChooserWidget filechooserwidget1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.TextView textviewVertex;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TextView textviewFragment;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Entry FilePath;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button SaveAs;
	private global::Gtk.Button compileShaders;
	private global::Gtk.Label label1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.filechooserwidget1 = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(0)));
		this.filechooserwidget1.Name = "filechooserwidget1";
		this.vbox1.Add (this.filechooserwidget1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.filechooserwidget1]));
		w1.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.textviewVertex = new global::Gtk.TextView ();
		this.textviewVertex.CanFocus = true;
		this.textviewVertex.Name = "textviewVertex";
		this.GtkScrolledWindow3.Add (this.textviewVertex);
		this.vbox1.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow3]));
		w3.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textviewFragment = new global::Gtk.TextView ();
		this.textviewFragment.CanFocus = true;
		this.textviewFragment.Name = "textviewFragment";
		this.GtkScrolledWindow2.Add (this.textviewFragment);
		this.vbox1.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow2]));
		w5.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("play");
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("pause");
		this.hbox1.Add (this.button2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("stop");
		this.hbox1.Add (this.button3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button3]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.FilePath = new global::Gtk.Entry ();
		this.FilePath.CanFocus = true;
		this.FilePath.Name = "FilePath";
		this.FilePath.IsEditable = true;
		this.FilePath.InvisibleChar = '●';
		this.vbox2.Add (this.FilePath);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.FilePath]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.SaveAs = new global::Gtk.Button ();
		this.SaveAs.CanFocus = true;
		this.SaveAs.Name = "SaveAs";
		this.SaveAs.UseUnderline = true;
		this.SaveAs.Label = global::Mono.Unix.Catalog.GetString ("Save As");
		this.hbox2.Add (this.SaveAs);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.SaveAs]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w12.Position = 3;
		// Container child hbox1.Gtk.Box+BoxChild
		this.compileShaders = new global::Gtk.Button ();
		this.compileShaders.CanFocus = true;
		this.compileShaders.Name = "compileShaders";
		this.compileShaders.UseUnderline = true;
		this.compileShaders.Label = global::Mono.Unix.Catalog.GetString ("Compile Shaders");
		this.hbox1.Add (this.compileShaders);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.compileShaders]));
		w13.PackType = ((global::Gtk.PackType)(1));
		w13.Position = 4;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("welcome to ShaderCrate");
		this.vbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 637;
		this.DefaultHeight = 740;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.filechooserwidget1.FileActivated += new global::System.EventHandler (this.OnFilechooserwidget1FileActivated);
		this.filechooserwidget1.CurrentFolderChanged += new global::System.EventHandler (this.OnFilechooserwidget1CurrentFolderChanged);
		this.filechooserwidget1.UpdatePreview += new global::System.EventHandler (this.OnFilechooserwidget1UpdatePreview);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.FilePath.Changed += new global::System.EventHandler (this.OnFilePathChanged);
		this.SaveAs.Clicked += new global::System.EventHandler (this.OnSaveAsClicked);
		this.compileShaders.Clicked += new global::System.EventHandler (this.OnCompileShadersClicked);
	}
}
